
image: node:latest

cache:
  paths:
  - node_modules/
  
stages:
  - install
  - lint
  - codereview

install
  stage: install
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn lint

codereview:
  stage: codereview
  script: 
    
    - yarn codereview